FROM python:3.9-slim-buster
WORKDIR /app
RUN apt update && apt install -y libpq-dev gcc
COPY ./requirements.txt /app
RUN pip install -r requirements.txt
COPY . .
ENV FLAG=sudo{H4V3_T0_InJ3C1_W@Y_De3p3R}
EXPOSE 2304
RUN ["python3", "manage.py",  "migrate"]
RUN echo $FLAG
CMD ["python3", "manage.py",  "runserver", "0.0.0.0:2304","--insecure" ]